CREATE DATABASE BDPaySoft
GO
USE BDPaySoft

CREATE TABLE SALON
(
ID_Salon  int IDENTITY(1,1) NOT NULL PRIMARY KEY ,
Nombre VARCHAR(30) NOT NULL,
Estado VARCHAR(30) NOT NULL
)

CREATE TABLE MESA
(
ID_Mesa int IDENTITY (1,1) NOT NULL PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Salon int NOT NULL,
Estado_Vida VARCHAR(30),
Estado_Disponibilidad VARCHAR(30) NULL

)
